# Generated by Django 2.1.7 on 2019-04-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appcasescrip', models.CharField(max_length=200, verbose_name='用例名称')),
                ('appcasename', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('appcaseselect', models.BooleanField(verbose_name='是否选中')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'app测试用例',
                'verbose_name_plural': 'app测试用例',
            },
        ),
    ]
