# Generated by Django 2.1.7 on 2019-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcase',
            options={'verbose_name': 'APPUI测试用例', 'verbose_name_plural': 'APPUI测试用例'},
        ),
        migrations.AlterField(
            model_name='appcase',
            name='appcaseselect',
            field=models.CharField(max_length=200, verbose_name='是否选中'),
        ),
    ]
