# Generated by Django 2.1.7 on 2019-04-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_auto_20190405_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcase',
            options={'verbose_name': 'APP测试用例', 'verbose_name_plural': 'APP测试用例'},
        ),
    ]
