# Generated by Django 2.1.7 on 2019-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0003_auto_20190405_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcase',
            name='appcaseselect',
            field=models.BooleanField(verbose_name='是否选中'),
        ),
    ]
