# Generated by Django 2.1.7 on 2019-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=200, verbose_name='手机平台')),
                ('platformVersion', models.CharField(max_length=200, verbose_name='手机平台版本号')),
                ('deviceName', models.CharField(max_length=200, verbose_name='手机型号')),
                ('udid', models.IntegerField(verbose_name='手机设备号')),
                ('port', models.CharField(max_length=200, verbose_name='端口号')),
                ('deviceselect', models.BooleanField(verbose_name='是否选中')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'APP系统设置',
                'verbose_name_plural': 'APP系统设置',
            },
        ),
    ]
