# Generated by Django 2.1.7 on 2019-04-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setapp',
            name='port',
            field=models.IntegerField(verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='setapp',
            name='udid',
            field=models.CharField(max_length=200, verbose_name='手机设备号'),
        ),
    ]
