# Generated by Django 2.1.7 on 2019-04-06 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_auto_20190405_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='setapp',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
